export const SET_GLOBAL_STATE = 'SET_GLOBAL_STATE';

export const FETCH_CITIES_START = 'FETCH_CITIES_START';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR';

export const FETCH_COUNTRY_START = 'FETCH_COUNTRY_START';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_ERROR = 'FETCH_COUNTRY_ERROR';

export const FETCH_SHORES_START = 'FETCH_SHORES_START';
export const FETCH_SHORES_SUCCESS = 'FETCH_SHORES_SUCCESS';
export const FETCH_SHORES_ERROR = 'FETCH_SHORES_ERROR';
